apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWcucWRvcy5kZG5zLm5ldCI6eyJ1c2VybmFtZSI6ImJvYiIsInBhc3N3b3JkIjoiYm9iIiwiYXV0aCI6IlltOWlPbUp2WWc9PSJ9fX0=
kind: Secret
metadata:
  name: myrepo
  namespace: gardentest-rich  
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"

type: kubernetes.io/dockerconfigjson