apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerapp
  namespace: gardentest-rich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumerapp1
  template:
    metadata:
      labels:
        app: consumerapp1
    spec:
      containers:
      - image: reg.qdos.ddns.net/gardentest-rich/consumerapp1-build:v-bald48d7f7
        name: consumerapp1
      imagePullSecrets:
      - name: myrepo
  

