apiVersion: v1
kind: Deployment
metadata:
  name: consumerapp
  namespace: gardentest-rich
spec:
  replicas: 1
  metadata:
    labels:
      app: consumerapp
  imagePullSecrets:
  - name: myrepo
  
  template:
    metadata:
      labels:
        app: cosnumerapp
    spec:
      containers:
        - name: consumerapp1-build:v-bald48d7f7
  

