apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWcucWRvcy5kZG5zLm5ldCI6eyJ1c2VybmFtZSI6ImJvYiIsInBhc3N3b3JkIjoiYm9iIiwiYXV0aCI6IlltOWlPbUp2WWc9PSJ9fX0=
kind: Secret
metadata:
  name: myrepo
  namespace: gardentest-rich  
type: kubernetes.io/dockerconfigjson