apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gardentest-cert
  namespace: gardentest-rich
spec:
  secretName: gardentest-tls-secret
  issuerRef:
    name: gardentest-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - web.gardentest.dev
    - consumer.gardentest.dev